name: CI

on:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]
  workflow_dispatch:

jobs:
  build-test-sbom:
    uses: ./.github/workflows/build-test-sbom.yml
    permissions:
      contents: read
      security-events: write
